### ISSUE TITLE
When trying to send message to contacts: Undefined variable: contact

### ISSUE THREAD

**Issue by ifuratdev** [luyadev/luya-module-addressbook#2]
### What steps will reproduce the problem?
When trying to send message to contacts an error occurs "Undefined variable: contact
I have tried different versions of php, still receiving the same error

### What is the expected result?
message should be sent

### What do you get instead? (A Screenshot can help us a lot!)

<img width="938" alt="Undefined variable-contact-error" src="https://user-images.githubusercontent.com/18122838/61748902-17fccd80-adaa-11e9-8f36-e9ae09996857.png">

### Additional infos

| Q                | A
| ---------------- | ---
| LUYA Version     | 
| PHP Version      |7.3.5
| Platform         | wamp64 - version 3.1.9.
| Operating system | Windows 10.

**Comment by nadar** [comment]
Thanks for the report, seems to be a bug.

**Comment by ifuratdev** [comment]
thanks for your quick response, if the log will help below is the log

2019-07-23 21:23:29 [::1][-][td38jeh1efc5j495estll2bhv9][error][yii\base\ErrorException:8] yii\base\ErrorException: Undefined variable: contact in C:\i_server\wamp64\www\luya\luya-kickstarter\vendor\luyadev\luya-module-addressbook\src\admin\views\aws\groupemail\index.php:13
Stack trace:
#0 C:\i_server\wamp64\www\luya\luya-kickstarter\vendor\yiisoft\yii2\base\View.php(257): luya\admin\ngrest\base\ActiveWindowView->renderPhpFile()
#1 C:\i_server\wamp64\www\luya\luya-kickstarter\vendor\yiisoft\yii2\base\View.php(156): luya\admin\ngrest\base\ActiveWindowView->renderFile()
#2 C:\i_server\wamp64\www\luya\luya-kickstarter\vendor\luyadev\luya-module-admin\src\ngrest\base\ActiveWindow.php(334): luya\admin\ngrest\base\ActiveWindowView->render()
#3 C:\i_server\wamp64\www\luya\luya-kickstarter\vendor\luyadev\luya-module-addressbook\src\admin\aws\GroupEmailActiveWindow.php(21): luya\addressbook\admin\aws\GroupEmailActiveWindow->render()
#4 C:\i_server\wamp64\www\luya\luya-kickstarter\vendor\luyadev\luya-module-admin\src\ngrest\render\RenderActiveWindow.php(25): luya\addressbook\admin\aws\GroupEmailActiveWindow->index()
#5 C:\i_server\wamp64\www\luya\luya-kickstarter\vendor\luyadev\luya-module-admin\src\ngrest\NgRest.php(58): luya\admin\ngrest\render\RenderActiveWindow->render()
#6 C:\i_server\wamp64\www\luya\luya-kickstarter\vendor\luyadev\luya-module-admin\src\ngrest\base\Api.php(722): luya\admin\ngrest\NgRest->render()
#7 C:\i_server\wamp64\www\luya\luya-kickstarter\vendor\yiisoft\yii2\base\InlineAction.php(57): luya\addressbook\admin\apis\GroupController->actionActiveWindowRender()
#8 C:\i_server\wamp64\www\luya\luya-kickstarter\vendor\yiisoft\yii2\base\InlineAction.php(57): ::call_user_func_array:{C:\i_server\wamp64\www\luya\luya-kickstarter\vendor\yiisoft\yii2\base\InlineAction.php:57}()
#9 C:\i_server\wamp64\www\luya\luya-kickstarter\vendor\yiisoft\yii2\base\Controller.php(157): yii\base\InlineAction->runWithParams()
#10 C:\i_server\wamp64\www\luya\luya-kickstarter\vendor\yiisoft\yii2\base\Module.php(528): luya\addressbook\admin\apis\GroupController->runAction()
#11 C:\i_server\wamp64\www\luya\luya-kickstarter\vendor\yiisoft\yii2\web\Application.php(103): luya\web\Application->runAction()
#12 C:\i_server\wamp64\www\luya\luya-kickstarter\vendor\luyadev\luya-core\web\Application.php(46): luya\web\Application->handleRequest()
#13 C:\i_server\wamp64\www\luya\luya-kickstarter\vendor\yiisoft\yii2\base\Application.php(386): luya\web\Application->handleRequest()
#14 C:\i_server\wamp64\www\luya\luya-kickstarter\vendor\luyadev\luya-core\base\Boot.php(266): luya\web\Application->run()
#15 C:\i_server\wamp64\www\luya\luya-kickstarter\vendor\luyadev\luya-core\base\Boot.php(208): luya\Boot->applicationWeb()
#16 C:\i_server\wamp64\www\luya\luya-kickstarter\public_html\index.php(8): luya\Boot->run()
#17 {main}
[Undefined variable-contact-error.txt]


(https://github.com/luyadev/luya-module-addressbook/files/3424210/Undefined.variable-contact-error.txt)

**Comment by ifuratdev** [comment]
BTW, I faced the same error with another module, i don't remember which one exactly but it think it was the SMSNewsletter module.

**Comment by nadar** [comment]
> BTW, I faced the same error with another module, i don't remember which one exactly but it think it was the SMSNewsletter module.

@ifuratdev please create the issue with a "report" and details in the associated repo. Thanks

**Comment by ifuratdev** [comment]
I have updated to the latest fix, but now getting a different error

Class 'luya\admin\ngrest\aw\CallbackFormWidget' not found

I'm using luya-module-admin version 2.1.0

**Comment by nadar** [comment]
Please create a new issue for a new error :-) Thanks

**Comment by ifuratdev** [comment]
sure :)
