### ISSUE TITLE
Class 'luya\admin\ngrest\aw\CallbackFormWidget' not found

### ISSUE THREAD

**Issue by ifuratdev** [luyadev/luya-module-addressbook#3]
### What steps will reproduce the problem?

When trying to send message to contacts an error occurs "
Class 'luya\admin\ngrest\aw\CallbackFormWidget' not found

I'm using luya-module-admin version 2.1.0

Note this is related to:
https://github.com/luyadev/luya-module-addressbook/issues/2

### What is the expected result?
message should be sent

### Additional infos

| Q                | A
| ---------------- | ---
| LUYA Version     | 
| PHP Version      |
| Platform         | Apache/XAMPP/MAMPP/etc.
| Operating system | Windows/Linux Server/OSX/etc.

**Comment by nadar** [comment]
Yes the widget has been removed in version 2.0 of admin module, i will replace them.

**Comment by ifuratdev** [comment]
perfect thanks nadar.
Note:
Your forgot to create a new release for the tag 1.0.3 :)
