### ISSUE TITLE
Bootstrap Style not rendered/missing in GroupEmailActiveWindow

### ISSUE THREAD

**Issue by czcpf** [luyadev/luya-module-addressbook#5]
### What steps will reproduce the problem?
1. Fresh install of luya-kickstarter-bootstrap4
2. migrate and import according to general setup of kickstarter application
3. install your module
4. composer require luyadev/luya-module-addressbook
5. add modules to config file
6. run migrate &  import
7. login to admin, grant permissions to the module, create group & contact
8. navigate to group
9. hover over the new mail icon to mail the group and click to open the Active Window
10. Observe the non-styled Active Window
### What is the expected result?
An Active Window with Bootstrap styles assigned and also without "False" in the modal header window.
<img width="881" alt="Screen Shot 2022-03-04 at 6 21 51 PM" src="https://user-images.githubusercontent.com/88215293/156858948-84b100be-e8e6-4c01-a1c2-d2cdf2948160.png">

### What do you get instead? (A Screenshot can help us a lot!)
<img width="1591" alt="Screen Shot 2022-03-04 at 6 18 07 PM" src="https://user-images.githubusercontent.com/88215293/156858757-16f4d901-64da-48c6-b371-6a3ab4f93f9b.png">

### LUYA Check ouput (run this script and post the result: [luyacheck.php](https://gist.github.com/nadar/022f890e064c068e75ce6178cd14a09e))
1: [in_array('mod_rewrite', apache_get_modules())] true
2: [ini_get('short_open_tag')] ''
3: [ini_get('error_reporting')] '32767'
4: [phpversion()] '8.0.9'
5: [php_ini_loaded_file()] '/usr/local/etc/php/8.0/php.ini'
6: [php_sapi_name()] 'apache2handler'
7: [isset($_SERVER['SERVER_SOFTWARE']) ? $_SERVER['SERVER_SOFTWARE'] : unknown] 'Apache/2.4.48 (Unix) OpenSSL/1.1.1k PHP/8.0.9'

### Additional infos

| Q                | A
| ---------------- | ---
| LUYA Version     | 4.0.0.0
| PHP Version      |8.0.9
| Platform         | Apache/2.4.48
| Operating system | OSX

**Comment by nadar** [comment]
hi @czcpf 

That's one of the oldest modules which was mainly for demo use case. But i will take a look next week. Thanks for the report
